### ISSUE TITLE
[Wrath] Conjure Mana Gem always visible

### ISSUE THREAD

**Issue by olamm2k** [kvakvs/BuffomatClassic#114] opened 2023-01-18 13:22 UTC
Most likely due to the C_Container changes in 3.4.1 (https://wowpedia.fandom.com/wiki/Patch_3.4.1/API_changes), Conjure Mana Gem is always showing, even when it has full charges.

![image](https://user-images.githubusercontent.com/179024/213182321-31a9340f-f572-488d-9bec-f3bac790a1ef.png)

**Comment by jdelvare** [comment] 2023-01-18 19:58
Duplicate of bug #113.

**Comment by jdelvare** [comment] 2023-05-06 14:36
Fixed, can be closed.

**Closed** 2023-05-06 14:57 UTC
